name: WordPress Theme CI/CD

on:
  workflow_call:
    inputs:
      assets:
        type: boolean
        description: Whether to build assets
        default: true
        required: false
      assets_lint:
        type: string
        description: Command to lint assets before building
        default: npm run lint
        required: false
      composer_cache_key_prefix:
        type: string
        description: Cache key prefix for composer install
        default: v1
        required: false
      deploy_branch:
        type: string
        description: Name of the branch where deployments should happen or empty string to disable deployments
        default: main
        required: false
      php_version:
        type: number
        description: Major (and optional minor) version number of PHP to use
        default: 7.4
        required: false

jobs:
  php_codesniffer:
    name: PHP Coding Standards
    runs-on: ubuntu-18.04
    # Skip code style check with [skip tests] in latest commit message and also
    # for bot actions.
    if: '!endsWith(github.actor, ''[bot]'') && !contains(github.event.head_commit.message, ''[skip tests]'')'
    steps:
      - uses: actions/checkout@v2
      - uses: projectcosmic/gh-actions/.github/actions/setup-composer-install@3.x
        with:
          cache_key_prefix: ${{ inputs.composer_cache_key_prefix }}
          php_version: ${{ inputs.php_version }}
      - run: ./vendor/bin/phpcs --runtime-set ignore_warnings_on_exit 1 --report-full
  assets:
    name: Build Assets
    runs-on: ubuntu-18.04
    # Run job on human-initiated events or dependabot npm pull request branch
    # pushes.
    if: |
      inputs.assets
      && (!endsWith(github.actor, '[bot]') || startsWith(github.ref, 'refs/heads/dependabot/npm_and_yarn/'))
      && !contains(github.event.head_commit.message, '[skip assets]')
    steps:
      - uses: actions/checkout@v2
      - id: version
        run: echo "::set-output name=node::$(jq '.volta.node' package.json --raw-output)"
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.version.outputs.node }}
          cache: npm
      - run: npm install
      - name: Run lint
        run: ${{ inputs.assets_lint }}
        if: inputs.assets_lint
      - run: npm run build
      - uses: actions/upload-artifact@v2
        if: github.ref == format('refs/heads/{0}', inputs.deploy_branch)
        with:
          name: assets
          path: dist
  deploy:
    name: Deploy
    runs-on: self-hosted
    needs:
      - php_codesniffer
      - assets
    # Run job on deployment branch, allowing skipped jobs but no failures or
    # cancellations.
    if: |
      github.ref == format('refs/heads/{0}', inputs.deploy_branch)
      && !cancelled()
      && needs.php_codesniffer.result != 'failure'
      && needs.assets.result != 'failure'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Parse Deploy Target Information
        id: target
        run: |
          if alias=`wp cli alias get @live 2>/dev/null`
          then
            echo "::set-output name=address::$(echo "$alias" | sed --regexp-extended --null-data 's/^.*\n?ssh:\s+([^\n]+)\n?.*/\1/')"
            echo "::set-output name=root::$(echo "$alias" | sed --regexp-extended --null-data 's/^.*\n?path:\s+([^\n]+)\n?.*/\1/')"
          fi
      - uses: actions/download-artifact@v2
        if: needs.assets.result == 'success'
        with:
          name: assets
          path: __gh-actions-assets__
      - name: Deploy assets
        if: needs.assets.result == 'success'
        run: |
          rsync __gh-actions-assets__/ ${{ steps.target.outputs.address }}:${{ steps.target.outputs.root }}/wp-content/themes/${{ github.event.repository.name }}/dist/ \
            --checksum \
            --chmod="Fgo-wx,Dgo-w" \
            --compress \
            --delete \
            --prune-empty-dirs \
            --recursive
      - run: git push ${{ steps.target.outputs.address }}:theme.git ${{ inputs.deploy_branch }} --force
