name: WordPress Theme CI/CD

on:
  workflow_call:
    inputs:
      assets:
        type: boolean
        description: Whether to build assets
        default: true
        required: false
      assets_lint:
        type: string
        description: Command to lint assets before building
        default: npm run lint
        required: false
      composer_cache_key_prefix:
        type: string
        description: Cache key prefix for composer install
        default: v1
        required: false
      deploy_branch:
        type: string
        description: Name of the branch where deployments should happen or empty string to disable deployments
        default: main
        required: false
      php_version:
        type: number
        description: Major (and optional minor) version number of PHP to use
        default: 7.4
        required: false

jobs:
  head_commit:
    name: 'Get HEAD Commit'
    runs-on: ubuntu-18.04
    if: |
      github.event_name == 'pull_request'
      && !endsWith(github.actor, '[bot]')
      && github.repository != github.event.pull_request.head.repo.full_name
    outputs:
      message: ${{ steps.data.outputs.message }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Extract HEAD commit data
        id: data
        run: |
          message="$(git log -1 --pretty=%B)"
          message="${message//'%'/'%25'}"
          message="${message//$'\n'/'%0A'}"
          message="${message//$'\r'/'%0D'}"
          echo "::set-output name=message::$message"
  php_codesniffer:
    name: PHP Coding Standards
    runs-on: ubuntu-18.04
    needs: head_commit
    # Skip when:
    # - triggered by a bot.
    # - [skip tests] is in the latest commit message.
    # - triggered for a PR event where the PR is in the same repo (favor the
    #   corresponding branch workflow run instead).
    if: |
      !endsWith(github.actor, '[bot]')
      && !contains(github.event.head_commit.message, '[skip tests]')
      && !cancelled()
      && needs.head_commit.result != 'failure'
      && !contains(needs.head_commit.outputs.message, '[skip tests]')
      && github.repository != github.event.pull_request.head.repo.full_name
    steps:
      - uses: actions/checkout@v2
      - uses: projectcosmic/gh-actions/.github/actions/setup-composer-install@v2.2.2
        with:
          cache_key_prefix: ${{ inputs.composer_cache_key_prefix }}
          php_version: ${{ inputs.php_version }}
      - run: ./vendor/bin/phpcs --runtime-set ignore_warnings_on_exit 1 --report-full
  assets:
    name: Build Assets
    runs-on: ubuntu-18.04
    needs: head_commit
    # Skip when:
    # - Asset build workflow configuration is false
    # - triggered by a bot and not an NPM or Yarn dependabot pull request.
    # - triggered by a human for a PR event where the PR is in the same repo
    #   (favor the corresponding branch workflow run instead).
    # - [skip assets] is in the latest commit message.
    if: |
      inputs.assets
      && (!endsWith(github.actor, '[bot]') || startsWith(github.head_ref, 'dependabot/npm_and_yarn/'))
      && (endsWith(github.actor, '[bot]') || github.repository != github.event.pull_request.head.repo.full_name)
      && !contains(github.event.head_commit.message, '[skip assets]')
      && !cancelled()
      && needs.head_commit.result != 'failure'
      && !contains(needs.head_commit.outputs.message, '[skip assets]')
    steps:
      - uses: actions/checkout@v2
      - id: version
        run: echo "::set-output name=node::$(jq '.volta.node' package.json --raw-output)"
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.version.outputs.node }}
          cache: npm
      - run: npm install
      - name: Run lint
        run: ${{ inputs.assets_lint }}
        if: inputs.assets_lint
      - run: npm run build
      - uses: actions/upload-artifact@v2
        if: github.ref == format('refs/heads/{0}', inputs.deploy_branch)
        with:
          name: assets
          path: dist
  deploy:
    name: Deploy
    runs-on: self-hosted
    needs:
      - php_codesniffer
      - assets
    # Skip when:
    # - the push event ref does not equal the deploy branch name.
    # - any dependent job failed (allow skipping).
    if: |
      github.ref == format('refs/heads/{0}', inputs.deploy_branch)
      && !cancelled()
      && needs.php_codesniffer.result != 'failure'
      && needs.assets.result != 'failure'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Parse Deploy Target Information
        id: target
        run: |
          if alias=`wp cli alias get @live 2>/dev/null`
          then
            echo "::set-output name=address::$(echo "$alias" | sed --regexp-extended --null-data 's/^.*\n?ssh:\s+([^\n]+)\n?.*/\1/')"
            echo "::set-output name=root::$(echo "$alias" | sed --regexp-extended --null-data 's/^.*\n?path:\s+([^\n]+)\n?.*/\1/')"
          fi
      - uses: actions/download-artifact@v2
        if: needs.assets.result == 'success'
        with:
          name: assets
          path: __gh-actions-assets__
      - name: Deploy assets
        if: needs.assets.result == 'success'
        run: |
          rsync __gh-actions-assets__/ ${{ steps.target.outputs.address }}:${{ steps.target.outputs.root }}/wp-content/themes/${{ github.event.repository.name }}/dist/ \
            --checksum \
            --chmod="Fgo-wx,Dgo-w" \
            --compress \
            --delete \
            --prune-empty-dirs \
            --recursive
      - run: git push ${{ steps.target.outputs.address }}:theme.git ${{ inputs.deploy_branch }} --force
